<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Reservation;
use App\Models\ReservationDays;
use App\Models\ReservationEquipments;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use GuzzleHttp\Promise\Create;
use Illuminate\Support\Facades\Hash;

class ReportsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('reservations')->truncate();
        DB::table('reservation_days')->truncate();
        DB::table('reservation_equipments')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $currentTimestamp = Carbon::now();

        $reservations=[
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Week of Welcome', 'startDate' => '2021-08-23','noOfdays' =>4, 'endDate' => '2021-08-26', 'occupants' => 300, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Worlds Teachers Day', 'startDate' => '2021-10-5','noOfdays' =>1, 'endDate' => '2021-10-5', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'International Womens Day', 'startDate' => '2022-03-08','noOfdays' =>1, 'endDate' => '2022-03-08', 'occupants' => 300, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 1, 'roleID' => 1, 'event' => 'Final Examination for Undergraduate Students', 'startDate' => '2022-06-11','noOfdays' =>8, 'endDate' => '2022-06-18', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 2, 'roleID' => 1, 'event' => 'Final Examination for Undergraduate and Graduate Level', 'startDate' => '2022-08-08','noOfdays' =>6, 'endDate' => '2022-08-13', 'occupants' => 300, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Week of Welcome', 'startDate' => '2023-08-22','noOfdays' =>4, 'endDate' => '2023-08-25', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Graduate Studies Orientation General Assembly', 'startDate' => '2023-09-16','noOfdays' =>1, 'endDate' => '2023-09-16', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 1, 'roleID' => 1, 'event' => 'Preliminary Examination Period for Undergraduate Level', 'startDate' => '2023-10-02','noOfdays' =>6, 'endDate' => '2023-10-07', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Announcement of Deans Lister of Previous Semester', 'startDate' => '2023-10-03','noOfdays' =>1, 'endDate' => '2023-10-03', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Wellness Period', 'startDate' => '2023-11-06','noOfdays' =>6, 'endDate' => '2023-11-11', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 3, 'roleID' => 1, 'event' => 'Pre-Final Examination for Non-Graduating Undergraduate Level Students', 'startDate' => '2023-12-04','noOfdays' =>6, 'endDate' => '2023-12-09', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'University Year-End Assembly and University Fellowship', 'startDate' => '2023-12-19','noOfdays' =>1, 'endDate' => '2023-12-19', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'USTP Charter Day 2023', 'startDate' => '2023-08-16','noOfdays' =>1, 'endDate' => '2023-08-16', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Birthday of Dr. Ricardo E. Rotoras', 'startDate' => '2023-09-18','noOfdays' =>1, 'endDate' => '2023-09-18', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Teaching Excellence Awards', 'startDate' => '2023-12-01','noOfdays' =>1, 'endDate' => '2023-12-01', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Death Anniversary of Dr. Ricardo E. Rotoras', 'startDate' => '2023-12-02','noOfdays' =>1, 'endDate' => '2023-12-02', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'USTP Praise Awards', 'startDate' => '2024-05-03','noOfdays' =>1, 'endDate' => '2024-05-03', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Saulog: Students Congress', 'startDate' => '2024-06-24','noOfdays' =>3, 'endDate' => '2024-06-26', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 7, 'roleID' => 1, 'event' => 'Alumni Week', 'startDate' => '2024-07-29','noOfdays' =>6, 'endDate' => '2024-08-03', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 1, 'roleID' => 1, 'event' => 'Final Examination for Graduate Level', 'startDate' => '2022-01-15','noOfdays' =>1, 'endDate' => '2022-01-15', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 2, 'roleID' => 1, 'event' => 'Final Examination for Undergraduate Level', 'startDate' => '2022-01-17','noOfdays' =>6, 'endDate' => '2022-01-22', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 3, 'roleID' => 1, 'event' => 'Preliminary Examination for Undergraduate Level', 'startDate' => '2022-03-07','noOfdays' =>6, 'endDate' => '2022-03-12', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 2, 'roleID' => 1, 'event' => 'Commencement Exercises', 'startDate' => '2022-08-22','noOfdays' =>5, 'endDate' => '2022-08-26', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 1, 'roleID' => 1, 'event' => 'Final Examination for Non-Graduating Graduate Level Students', 'startDate' => '2024-01-08','noOfdays' =>6, 'endDate' => '2024-01-13', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 3, 'roleID' => 1, 'event' => 'Final Examination for Non-Graduating Undergraduate Level Students', 'startDate' => '2024-01-15','noOfdays' =>10, 'endDate' => '2024-01-24', 'occupants' => 350, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 4, 'roleID' => 1, 'event' => 'Group Discussion', 'startDate' => '2023-10-15','noOfdays' =>1, 'endDate' => '2023-10-15', 'occupants' => 20, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 5, 'roleID' => 1, 'event' => 'Meeting', 'startDate' => '2022-06-06','noOfdays' =>1, 'endDate' => '2022-06-06', 'occupants' => 20, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['userID' => 1, 'facilityID' => 6, 'roleID' => 1, 'event' => 'Workshop', 'startDate' => '2022-06-09','noOfdays' =>1, 'endDate' => '2024-01-24', 'occupants' => 50, 'status' => 'APPROVED', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],


        ];
        Reservation::insert($reservations);

        $reservationsDays=[
            ['reservationID' => 1, 'days' => 1, 'date' => '2021-08-23', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 1, 'days' => 2, 'date' => '2021-08-24', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 1, 'days' => 3, 'date' => '2021-08-25', 'startTime' => '08:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 1, 'days' => 4, 'date' => '2021-08-26', 'startTime' => '08:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 2, 'days' => 1, 'date' => '2021-10-05', 'startTime' => '08:00:00', 'endTime' => '18:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 3, 'days' => 1, 'date' => '2022-03-08', 'startTime' => '10:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 1, 'date' => '2022-06-11', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 2, 'date' => '2022-06-12', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 3, 'date' => '2022-06-13', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 4, 'date' => '2022-06-14', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 5, 'date' => '2022-06-15', 'startTime' => '08:00:00', 'endTime' => '10:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 6, 'date' => '2022-06-16', 'startTime' => '08:00:00', 'endTime' => '10:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 7, 'date' => '2022-06-17', 'startTime' => '08:00:00', 'endTime' => '10:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'days' => 8, 'date' => '2022-06-18', 'startTime' => '08:00:00', 'endTime' => '10:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'days' => 1, 'date' => '2022-08-08', 'startTime' => '08:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'days' => 2, 'date' => '2022-08-09', 'startTime' => '08:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'days' => 3, 'date' => '2022-08-10', 'startTime' => '08:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'days' => 4, 'date' => '2022-08-11', 'startTime' => '08:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'days' => 5, 'date' => '2022-08-12', 'startTime' => '08:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'days' => 6, 'date' => '2022-08-13', 'startTime' => '08:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'days' => 1, 'date' => '2023-08-22', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'days' => 2, 'date' => '2023-08-23', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'days' => 3, 'date' => '2023-08-24', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'days' => 4, 'date' => '2023-08-25', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 7, 'days' => 1, 'date' => '2023-09-16', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'days' => 1, 'date' => '2023-10-02', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'days' => 2, 'date' => '2023-10-02', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'days' => 3, 'date' => '2023-10-02', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'days' => 4, 'date' => '2023-10-02', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'days' => 5, 'date' => '2023-10-02', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'days' => 6, 'date' => '2023-10-02', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 9, 'days' => 1, 'date' => '2023-10-03', 'startTime' => '08:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'days' => 1, 'date' => '2023-11-06', 'startTime' => '10:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'days' => 2, 'date' => '2023-11-07', 'startTime' => '10:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'days' => 3, 'date' => '2023-11-08', 'startTime' => '10:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'days' => 4, 'date' => '2023-11-09', 'startTime' => '10:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'days' => 5, 'date' => '2023-11-10', 'startTime' => '10:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'days' => 6, 'date' => '2023-11-11', 'startTime' => '10:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'days' => 1, 'date' => '2023-12-04', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'days' => 2, 'date' => '2023-12-05', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'days' => 3, 'date' => '2023-12-06', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'days' => 4, 'date' => '2023-12-07', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'days' => 5, 'date' => '2023-12-08', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'days' => 6, 'date' => '2023-12-09', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 12, 'days' => 1, 'date' => '2023-12-19', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 13, 'days' => 1, 'date' => '2023-08-16', 'startTime' => '09:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 14, 'days' => 1, 'date' => '2023-09-18', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 15, 'days' => 1, 'date' => '2023-12-01', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 16, 'days' => 1, 'date' => '2023-12-02', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 17, 'days' => 1, 'date' => '2024-05-03', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'days' => 1, 'date' => '2024-06-24', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'days' => 2, 'date' => '2024-06-25', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'days' => 3, 'date' => '2024-06-26', 'startTime' => '10:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'days' => 1, 'date' => '2024-07-29', 'startTime' => '09:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'days' => 2, 'date' => '2024-07-30', 'startTime' => '09:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'days' => 3, 'date' => '2024-07-31', 'startTime' => '09:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'days' => 4, 'date' => '2024-08-01', 'startTime' => '09:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'days' => 5, 'date' => '2024-07-02', 'startTime' => '09:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'days' => 6, 'date' => '2024-07-03', 'startTime' => '09:00:00', 'endTime' => '17:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 20, 'days' => 1, 'date' => '2022-01-15', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'days' => 1, 'date' => '2022-01-17', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'days' => 2, 'date' => '2022-01-18', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'days' => 3, 'date' => '2022-01-19', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'days' => 4, 'date' => '2022-01-20', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'days' => 5, 'date' => '2022-01-21', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'days' => 6, 'date' => '2022-01-22', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'days' => 1, 'date' => '2022-03-07', 'startTime' => '09:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'days' => 2, 'date' => '2022-03-08', 'startTime' => '09:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'days' => 3, 'date' => '2022-03-09', 'startTime' => '09:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'days' => 4, 'date' => '2022-03-10', 'startTime' => '09:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'days' => 5, 'date' => '2022-03-11', 'startTime' => '09:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'days' => 6, 'date' => '2022-03-12', 'startTime' => '09:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 23, 'days' => 1, 'date' => '2022-08-22', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 23, 'days' => 2, 'date' => '2022-08-23', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 23, 'days' => 3, 'date' => '2022-08-24', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 23, 'days' => 4, 'date' => '2022-08-25', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 23, 'days' => 5, 'date' => '2022-08-26', 'startTime' => '08:00:00', 'endTime' => '15:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'days' => 1, 'date' => '2024-01-08', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'days' => 2, 'date' => '2024-01-09', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'days' => 3, 'date' => '2024-01-10', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'days' => 4, 'date' => '2024-01-11', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'days' => 5, 'date' => '2024-01-12', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'days' => 6, 'date' => '2024-01-13', 'startTime' => '08:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 1, 'date' => '2024-01-15', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 2, 'date' => '2024-01-16', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 3, 'date' => '2024-01-17', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 4, 'date' => '2024-01-18', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 5, 'date' => '2024-01-19', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 6, 'date' => '2024-01-20', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 7, 'date' => '2024-01-21', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 8, 'date' => '2024-01-22', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 9, 'date' => '2024-01-23', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'days' => 10, 'date' => '2024-01-24', 'startTime' => '08:00:00', 'endTime' => '13:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 26, 'days' => 1, 'date' => '2023-10-15', 'startTime' => '09:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 27, 'days' => 1, 'date' => '2022-06-06', 'startTime' => '08:00:00', 'endTime' => '11:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 28, 'days' => 1, 'date' => '2022-06-09', 'startTime' => '09:00:00', 'endTime' => '12:00:00', 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],

        ];
        ReservationDays::insert($reservationsDays);
        $reservationsEquipments=[
            ['reservationID' => 1, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 1, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 1, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 1, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 1, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 2, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 2, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 2, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 2, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 2, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 3, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 3, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 3, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 3, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 3, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'equipmentID' => 1, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 4, 'equipmentID' => 2, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'equipmentID' => 3, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 5, 'equipmentID' => 4, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 6, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 7, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 7, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 7, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 7, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 7, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'equipmentID' => 1, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 8, 'equipmentID' => 2, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 9, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 9, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 9, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 9, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 9, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 10, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'equipmentID' => 5, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 11, 'equipmentID' => 6, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 12, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 12, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 12, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 12, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 12, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 13, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 13, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 13, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 13, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 13, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 14, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 14, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 14, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 14, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 14, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 15, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 15, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 15, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 15, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 15, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 16, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 16, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 16, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 16, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 16, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 17, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 17, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 17, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 17, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 17, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 18, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'equipmentID' => 14, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'equipmentID' => 15, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'equipmentID' => 16, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'equipmentID' => 17, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 19, 'equipmentID' => 18, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 20, 'equipmentID' => 1, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 20, 'equipmentID' => 2, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'equipmentID' => 3, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 21, 'equipmentID' => 4, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'equipmentID' => 5, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 22, 'equipmentID' => 6, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 23, 'equipmentID' => 2, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 23, 'equipmentID' => 3, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'equipmentID' => 1, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 24, 'equipmentID' => 2, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'equipmentID' => 4, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 25, 'equipmentID' => 5, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 26, 'equipmentID' => 7, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 26, 'equipmentID' => 8, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 26, 'equipmentID' => 9, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 27, 'equipmentID' => 10, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 27, 'equipmentID' => 11, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 27, 'equipmentID' => 12, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],
            ['reservationID' => 28, 'equipmentID' => 13, 'created_at' => $currentTimestamp, 'updated_at' => $currentTimestamp],

        ];
        ReservationEquipments::insert($reservationsEquipments);
    }
}
